// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const Action = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ActionCenter: "center",
    ActionFullscreen: "fullscreen",
    ActionHalfLeft: "half-left",
    ActionHalfRight: "half-right",
    ActionHalfTop: "half-top",
    ActionHalfBottom: "half-bottom",
    ActionUpperLeft: "upper-left",
    ActionUpperRight: "upper-right",
    ActionLowerLeft: "lower-left",
    ActionLowerRight: "lower-right",
    ActionNextThird: "next-third",
    ActionPrevThird: "prev-third",
    ActionTwoThirdsLeft: "two-thirds-left",
    ActionTwoThirdsRight: "two-thirds-right",
    ActionTwoThirdsCenter: "two-thirds-center",
    ActionNextDisplay: "next-display",
    ActionPrevDisplay: "prev-display",
    ActionNone: "none",

    /**
     * Special snap-only pseudo-actions produced when ⌥/⌘ is held while dragging
     * to a plain side edge; the snap controller resolves them to third columns.
     */
    ActionSnapThirdLeft: "snap-third-left",
    ActionSnapThirdRight: "snap-third-right",
};

export class GeneralSettings {
    /**
     * Creates a new GeneralSettings instance.
     * @param {Partial<GeneralSettings>} [$$source = {}] - The source object to create the GeneralSettings.
     */
    constructor($$source = {}) {
        if (!("launchAtLogin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["launchAtLogin"] = false;
        }
        if (!("showMenuBarIcon" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showMenuBarIcon"] = false;
        }
        if (!("enableAnimations" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableAnimations"] = false;
        }
        if (!("windowPadding" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowPadding"] = 0;
        }
        if (!("padFullscreen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["padFullscreen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneralSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GeneralSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneralSettings(/** @type {Partial<GeneralSettings>} */($$parsedSource));
    }
}

export class Hotkey {
    /**
     * Creates a new Hotkey instance.
     * @param {Partial<Hotkey>} [$$source = {}] - The source object to create the Hotkey.
     */
    constructor($$source = {}) {
        if (!("keyCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keyCode"] = 0;
        }
        if (!("modifiers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modifiers"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hotkey instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Hotkey}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hotkey(/** @type {Partial<Hotkey>} */($$parsedSource));
    }
}

export class HotkeySettings {
    /**
     * Creates a new HotkeySettings instance.
     * @param {Partial<HotkeySettings>} [$$source = {}] - The source object to create the HotkeySettings.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("bindings" in $$source)) {
            /**
             * @member
             * @type {{ [_ in Action]?: Hotkey }}
             */
            this["bindings"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeySettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeySettings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bindings" in $$parsedSource) {
            $$parsedSource["bindings"] = $$createField1_0($$parsedSource["bindings"]);
        }
        return new HotkeySettings(/** @type {Partial<HotkeySettings>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("general" in $$source)) {
            /**
             * @member
             * @type {GeneralSettings}
             */
            this["general"] = (new GeneralSettings());
        }
        if (!("hotkeys" in $$source)) {
            /**
             * @member
             * @type {HotkeySettings}
             */
            this["hotkeys"] = (new HotkeySettings());
        }
        if (!("snap" in $$source)) {
            /**
             * @member
             * @type {SnapSettings}
             */
            this["snap"] = (new SnapSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("general" in $$parsedSource) {
            $$parsedSource["general"] = $$createField0_0($$parsedSource["general"]);
        }
        if ("hotkeys" in $$parsedSource) {
            $$parsedSource["hotkeys"] = $$createField1_0($$parsedSource["hotkeys"]);
        }
        if ("snap" in $$parsedSource) {
            $$parsedSource["snap"] = $$createField2_0($$parsedSource["snap"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

export class SnapSettings {
    /**
     * Creates a new SnapSettings instance.
     * @param {Partial<SnapSettings>} [$$source = {}] - The source object to create the SnapSettings.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("restorePreviousSize" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restorePreviousSize"] = false;
        }
        if (!("zones" in $$source)) {
            /**
             * @member
             * @type {{ [_ in Zone]?: Action }}
             */
            this["zones"] = {};
        }
        if (!("zoneThickness" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["zoneThickness"] = 0;
        }
        if (!("activationDelayMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activationDelayMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapSettings}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("zones" in $$parsedSource) {
            $$parsedSource["zones"] = $$createField2_0($$parsedSource["zones"]);
        }
        return new SnapSettings(/** @type {Partial<SnapSettings>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Zone = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ZoneTopLeft: "top-left",
    ZoneTop: "top",
    ZoneTopRight: "top-right",
    ZoneLeft: "left",
    ZoneRight: "right",
    ZoneBottomLeft: "bottom-left",
    ZoneBottom: "bottom",
    ZoneBottomRight: "bottom-right",
};

// Private type creation functions
const $$createType0 = Hotkey.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = GeneralSettings.createFrom;
const $$createType3 = HotkeySettings.createFrom;
const $$createType4 = SnapSettings.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
