// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is bound to the frontend via Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * AXTrusted reports whether Accessibility permission is granted. The
 * onboarding UI polls this after sending the user to System Settings, so a
 * freshly granted permission also starts the engine — no relaunch needed.
 * @returns {$CancellablePromise<boolean>}
 */
export function AXTrusted() {
    return $Call.ByID(1930558327);
}

/**
 * @returns {$CancellablePromise<engine$0.Settings>}
 */
export function Get() {
    return $Call.ByID(2926682551).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ReconcileStartup re-applies settings whose state lives outside the process
 * (login item registration, tray visibility), so a settings file edited while
 * the app wasn't running — or drift in the login-item database — is corrected
 * at launch. Called from ApplicationDidFinishLaunching regardless of AX
 * permission.
 * @returns {$CancellablePromise<void>}
 */
export function ReconcileStartup() {
    return $Call.ByID(2878858104);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function RequestAXPermission() {
    return $Call.ByID(57360356);
}

/**
 * @returns {$CancellablePromise<engine$0.Settings>}
 */
export function RestoreDefaultHotkeys() {
    return $Call.ByID(3859344413).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ResumeHotkeys clears the suspend flag and, if the engine is running,
 * re-registers hotkeys from the current settings.
 * @returns {$CancellablePromise<void>}
 */
export function ResumeHotkeys() {
    return $Call.ByID(1740633685);
}

/**
 * @param {application$0.App | null} a
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(a) {
    return $Call.ByID(1064341430, a);
}

/**
 * SetPrefsFactory wires a constructor used to (re)create the prefs window if
 * it is missing or was destroyed. Wails v3 alpha offers no hide-on-close
 * window option and no IsDestroyed probe (checked against
 * WebviewWindowOptions / WebviewWindow docs), so main.go cancels the close
 * event and hides instead — this factory is the defensive fallback.
 * @param {any} f
 * @returns {$CancellablePromise<void>}
 */
export function SetPrefsFactory(f) {
    return $Call.ByID(3575272595, f);
}

/**
 * @param {application$0.WebviewWindow | null} w
 * @returns {$CancellablePromise<void>}
 */
export function SetPrefsWindow(w) {
    return $Call.ByID(276836711, w);
}

/**
 * @param {application$0.SystemTray | null} t
 * @returns {$CancellablePromise<void>}
 */
export function SetTray(t) {
    return $Call.ByID(742359983, t);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowPreferences() {
    return $Call.ByID(197307934);
}

/**
 * StartEngine registers hotkeys first, then the drag tap. Idempotent and safe
 * for concurrent callers (frontend AX polling can race the launch path).
 * engineOn latches only on full success: if StartDragTap fails, hotkeys stay
 * registered but engineOn remains false so the next AXTrusted poll retries.
 * A retry re-runs applyHotkeys, which is idempotent under hotkeysMu — it
 * starts by unregistering everything — so partial-hotkeys-then-retry is safe.
 * @returns {$CancellablePromise<void>}
 */
export function StartEngine() {
    return $Call.ByID(1368330785);
}

/**
 * SuspendHotkeys unregisters all global hotkeys and marks registration
 * suspended, so StartEngine/applySideEffects skip re-registering until
 * ResumeHotkeys is called. Used by the Hotkeys tab while recording a new
 * combo: Carbon otherwise intercepts the keydown before it reaches the
 * webview, making already-bound combos impossible to capture. Safe to call
 * even if the engine isn't running yet.
 * @returns {$CancellablePromise<void>}
 */
export function SuspendHotkeys() {
    return $Call.ByID(2284339606);
}

/**
 * @param {engine$0.Settings} next
 * @returns {$CancellablePromise<void>}
 */
export function Update(next) {
    return $Call.ByID(34876500, next);
}

// Private type creation functions
const $$createType0 = engine$0.Settings.createFrom;
