// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is bound to the frontend via Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * AXTrusted reports whether Accessibility permission is granted. The
 * onboarding UI polls this after sending the user to System Settings, so a
 * freshly granted permission also starts the engine — no relaunch needed.
 * @returns {$CancellablePromise<boolean>}
 */
export function AXTrusted() {
    return $Call.ByID(1930558327);
}

/**
 * @returns {$CancellablePromise<engine$0.Settings>}
 */
export function Get() {
    return $Call.ByID(2926682551).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function RequestAXPermission() {
    return $Call.ByID(57360356);
}

/**
 * @returns {$CancellablePromise<engine$0.Settings>}
 */
export function RestoreDefaultHotkeys() {
    return $Call.ByID(3859344413).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {application$0.App | null} a
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(a) {
    return $Call.ByID(1064341430, a);
}

/**
 * @param {application$0.WebviewWindow | null} w
 * @returns {$CancellablePromise<void>}
 */
export function SetPrefsWindow(w) {
    return $Call.ByID(276836711, w);
}

/**
 * @param {application$0.SystemTray | null} t
 * @returns {$CancellablePromise<void>}
 */
export function SetTray(t) {
    return $Call.ByID(742359983, t);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowPreferences() {
    return $Call.ByID(197307934);
}

/**
 * StartEngine registers hotkeys and the drag tap. Idempotent and safe for
 * concurrent callers (frontend AX polling can race the launch path).
 * @returns {$CancellablePromise<void>}
 */
export function StartEngine() {
    return $Call.ByID(1368330785);
}

/**
 * @param {engine$0.Settings} next
 * @returns {$CancellablePromise<void>}
 */
export function Update(next) {
    return $Call.ByID(34876500, next);
}

// Private type creation functions
const $$createType0 = engine$0.Settings.createFrom;
