import type { Settings } from "@tiles-spliter/shared";
// Generated by `wails3 generate bindings` (run from apps/desktop). The
// bindings are committed so fresh clones build without the Wails CLI; the
// desktop build script regenerates them when the CLI is available.
import * as SettingsService from "../bindings/github.com/GuilhermeVozniak/tiles-spliter/desktop/internal/app/settingsservice.js";

type Api = {
  getSettings: () => Promise<Settings>;
  updateSettings: (s: Settings) => Promise<void>;
  restoreDefaultHotkeys: () => Promise<Settings>;
  axTrusted: () => Promise<boolean>;
  requestAXPermission: () => Promise<boolean>;
};

let override: Partial<Api> | null = null;

/** Test-only escape hatch: swap in a mock implementation of the API. */
export function setApiForTests(mock: Partial<Api>) {
  override = mock;
}

export const getSettings: Api["getSettings"] = async () =>
  override?.getSettings
    ? override.getSettings()
    : ((await SettingsService.Get()) as Settings);

export const updateSettings: Api["updateSettings"] = async (s) => {
  if (override?.updateSettings) return override.updateSettings(s);
  await SettingsService.Update(s);
};

export const restoreDefaultHotkeys: Api["restoreDefaultHotkeys"] = async () =>
  override?.restoreDefaultHotkeys
    ? override.restoreDefaultHotkeys()
    : ((await SettingsService.RestoreDefaultHotkeys()) as Settings);

export const axTrusted: Api["axTrusted"] = async () =>
  override?.axTrusted ? override.axTrusted() : SettingsService.AXTrusted();

export const requestAXPermission: Api["requestAXPermission"] = async () =>
  override?.requestAXPermission
    ? override.requestAXPermission()
    : SettingsService.RequestAXPermission();
