import type { Settings } from "@tiles-spliter/shared";

// Generated by `wails3 generate bindings` into ./bindings (gitignored, not
// present until that CLI has been run against apps/desktop). Loaded lazily
// behind a try/catch so tests and plain-browser dev don't explode when the
// bindings module doesn't exist on disk yet.
type Api = {
  getSettings: () => Promise<Settings>;
  updateSettings: (s: Settings) => Promise<void>;
  restoreDefaultHotkeys: () => Promise<Settings>;
  axTrusted: () => Promise<boolean>;
  requestAXPermission: () => Promise<boolean>;
};

let override: Partial<Api> | null = null;

/** Test-only escape hatch: swap in a mock implementation of the API. */
export function setApiForTests(mock: Partial<Api>) {
  override = mock;
}

function isWailsRuntime(): boolean {
  return typeof window !== "undefined" && "_wails" in window;
}

async function bindings() {
  if (!isWailsRuntime()) {
    throw new Error(
      "Wails bindings are unavailable outside the desktop app runtime. " +
        "Use setApiForTests() to provide a mock in tests or plain-browser dev.",
    );
  }
  const bindingsPath =
    "../bindings/github.com/GuilhermeVozniak/tiles-spliter/desktop/internal/app/settingsservice";
  try {
    return await import(/* @vite-ignore */ bindingsPath);
  } catch (err) {
    throw new Error(
      "Wails bindings not found. Run `wails3 generate bindings` in apps/desktop first.",
      { cause: err },
    );
  }
}

export const getSettings: Api["getSettings"] = async () =>
  override?.getSettings ? override.getSettings() : (await bindings()).Get();

export const updateSettings: Api["updateSettings"] = async (s) =>
  override?.updateSettings ? override.updateSettings(s) : (await bindings()).Update(s);

export const restoreDefaultHotkeys: Api["restoreDefaultHotkeys"] = async () =>
  override?.restoreDefaultHotkeys
    ? override.restoreDefaultHotkeys()
    : (await bindings()).RestoreDefaultHotkeys();

export const axTrusted: Api["axTrusted"] = async () =>
  override?.axTrusted ? override.axTrusted() : (await bindings()).AXTrusted();

export const requestAXPermission: Api["requestAXPermission"] = async () =>
  override?.requestAXPermission
    ? override.requestAXPermission()
    : (await bindings()).RequestAXPermission();
